# Generated by Django 3.0.8 on 2020-09-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='personas_de_contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.BigIntegerField(blank=True, null=True)),
                ('cuantos_ninos', models.IntegerField()),
                ('edad_ninos', models.CharField(max_length=120)),
                ('dias', models.CharField(max_length=120)),
                ('horas_semana', models.IntegerField()),
                ('opciones_aplican1', models.BooleanField(verbose_name='Clases de inglés con anterioridad.')),
                ('opciones_aplican2', models.BooleanField(verbose_name='Grado preescolar y ha estado en escuela.')),
                ('metodo_comunicacion', models.CharField(choices=[('Email', 'Email'), ('Tel', 'Teléfono'), ('Ambos', 'Ambos')], max_length=15)),
            ],
        ),
    ]
