# Generated by Django 3.0.8 on 2020-09-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas_de_contacto',
            name='tel',
            field=models.BigIntegerField(blank=True),
        ),
    ]
